import type { VentureSeries, WebsiteMeasurement } from './venture-actions.js';

export function ventureActionsHtml(series: VentureSeries[], measurement: WebsiteMeasurement | null, esc: (s: unknown) => string): string {
  if (!series.length) return '';
  return '<section class="venture-progress"><h2>Now: test audience response</h2><p>Your research plan is approved. Use the existing posts, prepare a small set of adaptations, and collect evidence. No new proposal is needed to do this work.</p>'
    + series.map(s => '<h3>'+esc(s.title)+'</h3><div class="venture-table-wrap"><table class="venture-action-table"><thead><tr><th>Action</th><th>Status</th><th>Do next</th></tr></thead><tbody>'
      + '<tr><th scope="row">Match the existing posts</th><td>'+s.posts.length+' sources saved; '+s.posts.filter(p=>p.matches?.length).length+' matched to imported results</td><td>Publication links still need matching. Scheduling is owner-reported.</td></tr>'
      + '<tr><th scope="row">Prepare additional channels</th><td>'+s.posts.reduce((n,p)=>n+(p.draftCount||0),0)+' Content review rows</td><td>Open a source below. Start with at most two posts for LinkedIn and Bluesky. Nothing republishes to Substack.</td></tr>'
      + '<tr><th scope="row">Connect website measurements</th><td>'+(measurement
        ? 'Website totals retrieved: '+measurement.signups+' subscriber records, '+measurement.surveyCompletions+' completed surveys. Records may include imports; new website signups are not separated yet. These are not conversions attributed to these posts.'
        : 'Setup needed: the website stores signups and survey completions, but no aggregate has been retrieved yet. The database connection is needed for a read-only count.')
      + '</td><td><button type="button" data-website-refresh>Refresh website totals</button><p>Read-only live database query. Page visits and per-post attribution still need website integration.</p>'+(measurement?'<p>Last retrieved '+esc(measurement.capturedAt)+'</p>':'')+'</td></tr>'
      + '<tr><th scope="row">Review existing audience evidence</th><td>Available independently of this test</td><td><button type="button" data-venture-signals="existing">Review existing results</button> Older posts can inform audience and platform questions, but do not prove these hypotheses.</td></tr>'
      + '<tr><th scope="row">Read this test\'s results</th><td>Waiting for matched evidence</td><td><button type="button" data-venture-signals>Open this test in Signals</button></td></tr></tbody></table></div>'
      + '<h3>Content to adapt</h3><div class="venture-table-wrap"><table class="venture-action-table"><thead><tr><th>Source</th><th>Content status</th><th>Analytics match</th></tr></thead><tbody>'
      + s.posts.map(p => '<tr><th scope="row"><button type="button" data-venture-content="'+esc(p.contentSlug)+'">'+esc(p.title)+'</button></th><td>'+(p.draftCount===undefined?'Source needs checking':p.draftCount?p.draftCount+' review rows':'Ready to configure; no drafts yet')+'</td><td>'+(p.matches?.length?p.matches.length+' imported records':'Not matched yet')+'</td></tr>').join('')+'</tbody></table></div>'
      + '<h3>Questions we are testing</h3><ul>'+s.questions.map(q=>'<li>'+esc(q)+'</li>').join('')+'</ul>').join('')
    + '<p><strong>Then:</strong> wait for evidence and review what to continue or change. The 14-day outline is a guide, not a requirement to keep generating proposals. Phase completion and advancement still need their recorded evidence and your review.</p>'
    + '<button type="button" data-venture-documents>Read the approved research plan</button> <button type="button" data-venture-history>Context and workflow details</button></section>';
}

export function ventureSeriesSignalsHtml(series: VentureSeries[], measurement: WebsiteMeasurement | null, esc: (s: unknown) => string): string {
  if (!series.length) return '';
  return '<section><h3>Venture tests already underway</h3>'+series.map(s=>'<h4>'+esc(s.title)+'</h4><p>'+s.posts.length+' existing source posts linked from '+esc(s.ventureSlug)+'. Exploratory series, not a controlled comparison.</p><ul>'
    + s.questions.map(q=>'<li>'+esc(q)+'</li>').join('')+'</ul><p>Source matching: '+s.posts.filter(p=>p.matches?.length).length+' of '+s.posts.length+' have an exact text match in imported analytics. No result or winning platform is inferred.</p><ul>'+s.posts.map(p=>'<li>'+esc(p.title)+' · '+(p.matches?.length?p.matches.map(m=>esc(m.platform)+' #'+m.id+' ('+esc(m.postedAt||'date unknown')+')').join(', '):'awaiting matching publication record')+'</li>').join('')+'</ul><button type="button" class="sig-venture-open" data-slug="'+esc(s.ventureSlug)+'">Open Venture actions</button>').join('')
    + '<h4>Website measurement status</h4>'+(measurement ? '<p>'+measurement.signups+' subscriber records · '+measurement.surveyCompletions+' completed surveys · '+measurement.activeSubscribers+' active subscribers.</p><p>Site-wide database snapshot captured '+esc(measurement.capturedAt)+'. Earliest stored subscription timestamp: '+esc(measurement.firstSignupAt||'none')+'. Records may include imports; new website signups are not separated yet. Not attributed to this test. Survey completion is a saved submission, not a qualified response or proof of demand.</p>' : '<p>Signups and survey completions are stored by the website. Connection pending; no counts retrieved.</p>')
    + '<button type="button" data-website-refresh>Refresh website totals</button><p>Queries the live website database on request. Page visits: not connected. Per-post conversions: not attributed. Raw subscriber details and survey answers are not shared here.</p></section>';
}
