/** Self-contained renderers embedded in the local app. Values are escaped, never executable. */
export function contentReaderActionHtml(context: any, action: any, cards: any[], esc: (v: any) => string): string {
  const destinations = context?.destinations || [];
  const intended = context?.intended;
  const selected = action?.mode === 'destination' ? action.destinationId : action?.mode || '';
  const destination = destinations.find((d: any) => d.id === selected);
  const suggestion = cards.find((c: any) => c.kind === 'cta' && c.destinationId === selected && c.status !== 'dismissed');
  const origin = intended?.destinationId === selected ? 'From your Venture plan' : suggestion ? 'Suggested by the advisor' : 'Your choice';
  return '<section style="margin-top:26px"><h3>Reader’s next step</h3>' +
    (context?.ventureId ? '<p>Venture: <b>'+esc(context.ventureId)+'</b>'+ (context.goal ? ' · '+esc(context.goal) : '')+'</p>' : '<p>No Venture linked to this piece. Use its source or no CTA.</p>') +
    (intended ? '<p>From your Venture plan: '+esc(destinations.find((d:any)=>d.id===intended.destinationId)?.name || intended.destinationId)+' · '+esc(intended.reason)+'</p>' : '') +
    '<label>Where should readers go? <select id="contentReaderAction"><option value=""'+(!selected?' selected':'')+'>Keep the existing source-link default</option><option value="none"'+(selected==='none'?' selected':'')+'>No CTA for this piece</option>'+destinations.map((d:any)=>'<option value="'+esc(d.id)+'"'+(selected===d.id?' selected':'')+(d.status!=='ready'?' disabled':'')+'>'+esc(d.name)+' · '+esc(d.status)+'</option>').join('')+'</select></label>'+
    (!destinations.length && context?.ventureId ? '<p>No destinations registered yet. Add an existing essay, signup page, or resource in Venture → Reader destinations. No promotional link will be invented.</p>' : '')+
    (destination ? '<p><b>'+origin+'</b><br>'+esc(destination.benefit)+'<br>For: '+esc(destination.audience)+'<br>Reader action: '+esc(destination.action)+'<br><a href="'+esc(destination.url)+'" target="_blank" rel="noopener noreferrer">'+esc(destination.url)+'</a><br>Measurement: '+esc(destination.measurement)+'</p><label style="display:block">Why this helps readers of this piece<textarea id="contentReaderReason" rows="2" style="width:100%">'+esc(action?.reason||'')+'</textarea></label><label><input type="checkbox" id="contentReaderReviewed"'+(action?.reviewed?' checked':'')+'> I’ve checked that this destination exists and is a strong fit with useful reader value.</label>' : '')+
    '<p class="src">This choice is saved with the plan and shown with each draft. Nothing is published here.</p></section>';
}

export function ventureConversionsHtml(data: any, esc: (v: any) => string): string {
  const plan=data.plan;
  const fields = [['name','Name'],['audience','Who it helps'],['benefit','What it offers'],['action','CTA label / reader action'],['measurement','What to measure (or “Not connected yet”)'],['url','Existing HTTPS URL']];
  const row=(d:any)=>'<div data-conversion-row="'+esc(d.id)+'" style="margin:22px 0;padding:16px;border:1px solid var(--line)"><h4>'+esc(d.name)+'</h4>'+fields.map(([key,label])=>'<label style="display:block;margin:10px 0">'+label+'<input data-conversion-field="'+key+'" value="'+esc(d[key]||'')+'" style="display:block;width:100%"></label>').join('')+'<label>Status <select data-conversion-field="status">'+['proposed','building','ready','retired'].map(s=>'<option'+(s===d.status?' selected':'')+'>'+s+'</option>').join('')+'</select></label></div>';
  return '<h3>Reader destinations</h3><p>Keep the resources, signup pages and offers this Venture can point readers toward. Ready means the destination already exists. Saving here never publishes an asset or clears a phase.</p><label style="display:block">Conversion goal<textarea id="ventureConversionGoal" rows="2" style="width:100%">'+esc(plan.goal)+'</textarea></label>'+
    '<div class="venture-table-wrap"><table class="venture-action-table"><thead><tr><th>Destination</th><th>Status</th><th>Reader action</th></tr></thead><tbody>'+data.destinations.map((d:any)=>'<tr><td>'+esc(d.name)+'</td><td>'+esc(d.status)+'</td><td>'+esc(d.action)+'</td></tr>').join('')+'</tbody></table></div>'+
    '<details style="margin:20px 0"><summary>Add or edit destinations</summary>'+plan.destinations.map(row).join('')+'<div id="newConversionRows"></div><button type="button" data-conversion-add>Add a destination</button></details>'+
    '<h4>CTAs for Content pieces</h4><p>Optionally assign a destination here. Content checks the fit before drafting. Proposed or unfinished resources remain unavailable there.</p>'+data.pieces.map((p:any)=>{ const assignment=plan.assignments.find((a:any)=>a.contentId===p.id); return '<div data-conversion-piece="'+esc(p.id)+'" style="margin:16px 0"><b>'+esc(p.title)+'</b><label style="display:block">Destination <select data-conversion-assignment><option value="">Let the Content advisor check</option>'+data.destinations.map((d:any)=>'<option value="'+esc(d.id)+'"'+(assignment?.destinationId===d.id?' selected':'')+'>'+esc(d.name)+' · '+esc(d.status)+'</option>').join('')+'</select></label><input data-conversion-reason placeholder="Why this destination fits this piece" value="'+esc(assignment?.reason||'')+'" style="width:100%"></div>';}).join('')+
    '<button type="button" class="primary" data-conversion-save>Save destinations and assignments</button><p id="ventureConversionStatus" role="status"></p>';
}
