/** Self-contained renderers embedded in the local app. Values are escaped, never executable. */
export function contentReaderActionHtml(context: any, action: any, cards: any[], esc: (v: any) => string): string {
  const destinations = context?.destinations || [];
  const intended = context?.intended;
  const selected = action?.mode === 'destination' ? action.destinationId : action?.mode || '';
  const destination = destinations.find((d: any) => d.id === selected);
  const suggestion = cards.find((c: any) => c.kind === 'cta' && c.destinationId === selected && c.status !== 'dismissed');
  const origin = intended?.destinationId === selected ? (destination?.status==='linked'?'Already linked in this piece':'From your Venture plan') : suggestion ? 'Suggested by the advisor' : 'Your choice';
  return '<section style="margin-top:26px"><h3>Reader’s next step</h3>' +
    (destination ? '<p>'+esc(destination.action)+' <a href="'+esc(destination.url)+'" target="_blank" rel="noopener noreferrer">'+esc(destination.name)+'</a></p><p>'+esc(action?.reason||destination.benefit)+'</p><p class="src">'+esc(origin)+(destination.status==='linked'?'. Not live-verified.':'')+'</p>' : '<p>'+(selected==='none'?'No CTA for this piece.':'Keep the existing source link, if available.')+'</p>')+
    '<details><summary>Change destination or reasoning</summary>'+
    '<label>Where should readers go? <select id="contentReaderAction"><option value=""'+(!selected?' selected':'')+'>Keep the existing source-link default</option><option value="none"'+(selected==='none'?' selected':'')+'>No CTA for this piece</option>'+destinations.map((d:any)=>'<option value="'+esc(d.id)+'"'+(selected===d.id?' selected':'')+(!['ready','linked'].includes(d.status)?' disabled':'')+'>'+esc(d.name)+' · '+esc(d.status==='linked'?'Already linked in content':d.status)+'</option>').join('')+'</select></label>'+
    (!destinations.length && context?.ventureId ? '<p>No existing resources found yet. Venture will list linked essays and resources as they appear in your content or are built. No promotional link will be invented.</p>' : '')+
    (destination ? '<label style="display:block">Why this helps readers<textarea id="contentReaderReason" rows="2" style="width:100%">'+esc(action?.reason||'')+'</textarea></label><p class="src">Measurement: '+esc(destination.measurement)+'</p>' : '')+'</details>'+
    (destination?'<label style="display:block;margin-top:12px"><input type="checkbox" id="contentReaderReviewed"'+(action?.reviewed?' checked':'')+'> I’ve checked the link and its value for these readers.</label>':'')+'</section>';
}

export function ventureConversionsHtml(data: any, esc: (v: any) => string): string {
  const plan=data.plan;
  const fields = [['name','Name'],['audience','Who it helps'],['benefit','What it offers'],['action','CTA label / reader action'],['measurement','What to measure (or “Not connected yet”)'],['url','Existing HTTPS URL']];
  const rows=plan.destinations.map((d:any)=>'<div data-conversion-row="'+esc(d.id)+'" style="margin:22px 0;padding:16px;border:1px solid var(--line)"><h4>'+esc(d.name)+'</h4>'+fields.map(([key,label])=>'<label style="display:block;margin:10px 0">'+label+'<input data-conversion-field="'+key+'" value="'+esc(d[key]||'')+'" style="display:block;width:100%"></label>').join('')+'<label>Status <select data-conversion-field="status">'+['proposed','building','ready','retired'].map(s=>'<option'+(s===d.status?' selected':'')+'>'+s+'</option>').join('')+'</select></label></div>').join('');
  return '<h3>Essays and reader resources</h3><p>Collected automatically from this Venture’s content and resource work. Existing links stay with their posts; the Content advisor checks fit when suggesting alternatives. You do not need to assign every post here.</p>'+
    (plan.goal ? '<p><b>Reader goal:</b> '+esc(plan.goal)+'</p>' : '')+
    '<div class="venture-table-wrap"><table class="venture-action-table"><thead><tr><th>Resource</th><th>Status</th><th>Referenced by</th></tr></thead><tbody>'+data.destinations.map((d:any)=>'<tr><td>'+(d.url?'<a href="'+esc(d.url)+'" target="_blank" rel="noopener noreferrer">'+esc(d.name)+'</a>':esc(d.name))+'<br><span class="src">'+esc(d.kind||'Venture resource')+'</span></td><td>'+esc(d.status==='linked'?'Linked in existing content; not live-verified':d.status==='proposed'?'Planned / proposed':d.status==='building'?'Being built':d.status==='ready'?'Ready':'Retired')+'</td><td>'+((d.usedBy||[]).length?'<ul>'+d.usedBy.map((p:any)=>'<li>'+esc(p.title)+'</li>').join('')+'</ul>':'Not linked to a post yet')+'</td></tr>').join('')+'</tbody></table></div>'+
    (!data.destinations.length?'<p>No resources found yet. Essays and tools appear when linked in your content; lead magnets appear as Venture plans and builds them.</p>':'')+
    '<p class="src">Essays and existing tools are not lead magnets. Planned resources remain unavailable as CTAs until they are approved and live. This list updates from saved work when reopened.</p>'+
    '<details style="margin:20px 0"><summary>Manual additions and corrections (optional)</summary><p>Edit existing links in the source content. These overrides are for resources not captured there.</p><label style="display:block">Reader goal<textarea id="ventureConversionGoal" rows="2" style="width:100%">'+esc(plan.goal)+'</textarea></label>'+rows+'<div id="newConversionRows"></div><button type="button" data-conversion-add>Add a resource</button> <button type="button" class="primary" data-conversion-save>Save corrections</button></details><p id="ventureConversionStatus" role="status"></p>';
}
